### ISSUE TITLE
这是啥意思

### ISSUE THREAD

**Issue by cxs13991120** [CrushWater/DouDiZhuFuZhuQi#1]
pygame 2.5.2 (SDL 2.28.3, Python 3.8.0)
Hello from the pygame community. https://www.pygame.org/contribute.html
Traceback (most recent call last):
  File "斗地主辅助器.py", line 38, in <module>
    font = pygame.font.Font("阿里妈妈刀隶体.ttf", font_size)
FileNotFoundError: No file '阿里妈妈刀隶体.ttf' found in working directory 'C:\Users\Administrator\Downloads\DouDiZhuFuZhuQi-master'.

**Comment by CrushWater** [comment]
@cxs13991120 没有该字体，要不就改成默认系统字体吧，当时为了界面好看一点
